const demoResponse = [
  {
    id: 680,
    question: 'How can you display the top 10 number of lines of a file?',
    description: null,
    answers: {
      answer_a: 'head \u2212n 10 file.txt',
      answer_b: 'head -f 10 file.txt',
      answer_c: 'head --display-only 10 file.txt',
      answer_d: 'head -show 10 file.txt',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'true',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: 'BASH' }, { name: 'Linux' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 823,
    question: 'BASH stands for:',
    description: null,
    answers: {
      answer_a: 'Bourne Again SHell',
      answer_b: 'BAsic SHell',
      answer_c: 'Basic Async SHell',
      answer_d: null,
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'true',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: 'BASH' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 48,
    question:
      'Which of the answers listed below refers to a command used for invoking a text editor in Unix-like operating systems?',
    description: null,
    answers: {
      answer_a: 'edit',
      answer_b: 'notepad',
      answer_c: 'vi',
      answer_d: 'bcdedit',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'false',
      answer_c_correct: 'true',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_c',
    explanation: null,
    tip: null,
    tags: [{ name: 'Linux' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 654,
    question:
      'Which option can be used with \u2018rm\u2019 command to prompt for file removal?',
    description: null,
    answers: {
      answer_a: '-ask',
      answer_b: '-i',
      answer_c: '-c',
      answer_d: '-n',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'true',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [{ name: 'BASH' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 731,
    question:
      'How to compares the current state of the cluster against the state that the cluster would be in if the manifest was applied in Kubernetes?',
    description: null,
    answers: {
      answer_a: 'kubectl show -f ./my-manifest.yaml',
      answer_b: 'kubectl log -f ./my-manifest.yaml',
      answer_c: 'kubectl state -f ./my-manifest.yaml',
      answer_d: 'kubectl diff -f ./my-manifest.yaml',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'true',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [{ name: 'Kubernetes' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 662,
    question:
      'Which command can give first found difference between two file after comparing?',
    description: null,
    answers: {
      answer_a: 'diff',
      answer_b: 'cmp',
      answer_c: 'Common',
      answer_d: 'stat',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'true',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [{ name: 'BASH' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 1078,
    question:
      'If you see a directory with the following permissions `drwxrwxrxt`, would you be able to remove it?',
    description: null,
    answers: {
      answer_a: 'Only the owner of the folder can remove this folder',
      answer_b: 'Yes, we can remove it from any user',
      answer_c: 'We can remove it with the root user',
      answer_d: 'We can remove it only using the root user',
      answer_e: "No, this folder can't be remove.",
      answer_f: null,
    },
    multiple_correct_answers: 'true',
    correct_answers: {
      answer_a_correct: 'true',
      answer_b_correct: 'false',
      answer_c_correct: 'true',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: 'Linux' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 716,
    question:
      'An abstraction in kubernetes which defines a logical set of pods and a policy to access them.',
    description: null,
    answers: {
      answer_a: 'node',
      answer_b: 'cluster',
      answer_c: 'service',
      answer_d: 'set',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'false',
      answer_c_correct: 'true',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation:
      'A service is a grouping of pods that are running on the cluster. Services are "cheap" and you can have many services within the cluster.',
    tip: null,
    tags: [{ name: 'Kubernetes' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 686,
    question:
      'Which command can be used to write onto other currently logged in user\u2019s console output terminal.',
    description: null,
    answers: {
      answer_a: 'notify',
      answer_b: 'alert',
      answer_c: 'write',
      answer_d: 'broadcast',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'false',
      answer_c_correct: 'true',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: 'BASH' }, { name: 'Linux' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
  {
    id: 1080,
    question:
      'Which command do we need to use if we want to see all packages installed on the system (Ubuntu)',
    description: null,
    answers: {
      answer_a: 'dpkg -l',
      answer_b: 'packageall -l',
      answer_c: 'dpkg -a',
      answer_d: null,
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'true',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: 'Linux' }],
    category: 'Linux',
    difficulty: 'Easy',
  },
];
